stages:
  - setup
  - preupload
  - upload
  - cleanup

clone:
  stage: setup
  script:
    - cd
    - git clone http://gitlab.namibsun.net/namboy94/homepage.git

generate_statistics:
  stage: preupload
  script:
    - cd
    - cd homepage
    - git_stats generate
    - rsync -avP --delete-after git_stats/ www.krumreyh.de@ssh.strato.de:~/git_stats_pages/homepage

upload_to_strato:
  stage: upload
  script:
    - cd
    - rsync -avP --delete-after homepage/ www.krumreyh.de@ssh.strato.de:~/Homepage
    - ssh www.krumreyh.de@ssh.strato.de 'rsync -av --delete-after git_stats_pages Homepage/'

delete_clone:
  stage: cleanup
  script:
    - cd
    - rm -rf homepage


